[theme]
base = "light"
primaryColor = "#FF4500"
backgroundColor = "#F3F4F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#2D3142"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
